config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "metrics#index"

  resources :metrics do
    collection do 
      get 'action_plan'
      post 'create_action_plan'
      get 'julius_cap'
      get 'matthew_cap'
      get 'tyrone_cap'
      get 'elmer_cap'
    end
  end

  resources :qcms
  resources :agents
end

app/controllers/metrics_controller.rb
class MetricsController < ApplicationController
  def index
    @qcms = ActionPlan::QCM_LIST
  end

  def action_plan
  end

  def create_action_plan
    @action_plan = ActionPlan.new(action_plan_params)

    if @action_plan.save
      flash[:notice] = "Action Plan successfully created"
      redirect_to action_plan_metrics_path
    else
      flash[:success] = "Error"
      redirect_to :back
    end

  end

  def julius_cap
  end

  def matthew_cap
  end

  def tyrone_cap
  end

  def elmer_cap
  end

  private

  def action_plan_params
    params.require(:create_plan).permit(:qcm, :date, :agent, :specific_behavior, :measurable,
                                        :action, :relevant, :timebound, :why)
  end
end

app/helpers/metrics_helper.rb
module MetricsHelper
end

app/views/metrics/action_plan.html.erb
<center><h1>Smart Action Plan</h1></center>
<div class="top40"></div>
<div class="card side20 top20">
  <%= form_for "create_plan", url: create_action_plan_metrics_path, method: :post do |f| %>
    <div class="row">
      <div class="col-md-2">
        QCM: 
      </div>
      <div class="col-md-10">
        <%= f.select :qcm, ActionPlan::QCM_LIST, {include_blank: true}, class: 'form-control', style: "width: 250px;" %>
      </div>
    </div>
    <br/>
    <br/>
    <div class="row">
      <div class="col-md-2">
        Agent: 
      </div>
      <div class="col-md-10">
        <%= f.text_field :agent, class: 'form-control', style: 'width: 250px;' %>
      </div>
    </div>
    <br/>
    <br/>
    <div class="row">
      <div class="col-md-2">
        Input Date:
      </div>
      <div class="col-md-10">
        <%= f.date_field :date, class: 'text_area_width form-control input rounded-3' %>
      </div>
    </div>
    <br/>
    <br/>
    <div class="row">
      <div class="col-md-2">
        Specific Behavior: 
      </div>
      <div class="col-md-10">
        <%= f.text_area :specific_behavior, class: 'text_area_width form-control input rounded-3' %>
      </div>
    </div>
    <br/>
    <br/>
    <div class="row">
      <div class="col-md-2">
        Measurable: 
      </div>
      <div class="col-md-10">
        <%= f.text_area :measurable, class: 'text_area_width form-control input rounded-3' %>
      </div>
    </div>
    <br/>
    <br/>  
    <div class="row">
      <div class="col-md-2">
        Action: 
      </div>
      <div class="col-md-10">
        <%= f.text_area :action, class: 'text_area_width form-control input rounded-3' %>
      </div>
    </div>
    <br/>
    <br/>
    <%= f.submit 'Submit', class: 'btn btn-sm btn-primary' %>
    <div class="top20"></div>
  <% end %> 
</div>
<br/>
<br/>
<br/>
<br/>

app/views/metrics/index.html.erb
<center><h1>Smart Action Plan</h1></center>
  <table class="table">
	  <thead class="thead-dark">
	    <tr>
	      <th scope="col"></th>
	      <th scope="col">QCM</th>
	      <th scope="col">Team</th>
	      <th scope="col">Link</th>
	    </tr>
	  </thead>
	  <tbody>
			<% @qcms.each do |qcm| %>
	    <tr>
	      <th scope="row"></th>
	      <td><%= qcm[0] %></td>
	      <td><%= qcm[1] %></td>
	      <td><a href="metrics/<%= qcm[2] %>">View</a></td>
	    </tr>
			<% end %>
	  </tbody>
  </table>