config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "metrics#index"

  resources :metrics do
    collection do 
      get 'action_plan'
      post 'create_action_plan'
      get 'julius_cap'
      get 'matthew_cap'
      get 'tyrone_cap'
      get 'elmer_cap'
    end
  end

  resources :qcms
  resources :agents
end

app/models/qcm.rb
class Qcm < ApplicationRecord
end

app/controllers/qcms_controller.rb
class QcmsController < ApplicationController
  def index
    @qcms = Qcm.all
  end

  def new
  end

  def create
    qcm = Qcm.new(qcm_params)
    if qcm.save
      flash[:notice] = "Action Plan successfully created"
      redirect_to qcms_path
    else
      flash[:success] = "Error"
      redirect_to :back
    end
  end

  private

  def qcm_params
    params.require(:qcm).permit(:first_name, :last_name, :status)
  end

end

app/helpers/qcms_helper.rb
module QcmsHelper
end

app/views/qcms/index.html.erb
<h2><center>QCM list</center></h2>
<div class="top20"></div>
<%= link_to 'Create', new_qcm_path, class: 'btn btn-sm btn-primary' %>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col"></th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Team</th>
    </tr>
  </thead>
  <tbody>
    <% @qcms.each do |qcm| %>
    <tr>
      <th scope="row"></th>
      <td><%= qcm.first_name %></td>
      <td><%= qcm.last_name %></td>
      <td><%= qcm.team_name %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/qcms/new.html.erb
<h2><center>Create New QCM</center></h2>

<%= form_for Qcm.new do |f| %>
  <div class="row">
      <div class="col-md-2">
        First name
      </div>
      <div class="col-md-10">
        <%= f.text_field :first_name, class: 'form-control agent_form_width' %>
      </div>
    </div>
    <div class="top20"></div>
    <div class="row">
      <div class="col-md-2">
        Last name
      </div>
      <div class="col-md-10">
        <%= f.text_field :last_name, class: 'form-control agent_form_width' %>
      </div>
    </div>
    <%= f.hidden_field :status, value: 'active' %>
    <div class="top20"></div>
    <%= f.submit 'Submit', class: 'btn btn-sm btn-primary' %>
<% end %>