config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "metrics#index"

  resources :metrics do
    collection do 
      get 'action_plan'
      post 'create_action_plan'
      get 'julius_cap'
      get 'matthew_cap'
      get 'tyrone_cap'
      get 'elmer_cap'
    end
  end

  resources :qcms
  resources :agents
end

app/models/agent.rb
class Agent < ApplicationRecord
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  def index
    @agents = Agent.all
  end

  def new
    @agent = Agent.new
  end

  def create
    agent = Agent.new(agent_params)
    if agent.save
      flash[:notice] = "Agent successfully created"
      redirect_to agents_path
    else
      flash[:error] = "Error"
      redirect_to :back
    end
  end

  private

  def agent_params
    params.require(:agent).permit(:first_name, :last_name, :status)
  end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/views/agents/index.html.erb
<h2><center>Agent list</center></h2>
<div class="top20"></div>
<%= link_to 'Create', new_agent_path, class: 'btn btn-sm btn-primary' %>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col"></th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
    </tr>
  </thead>
  <tbody>
    <% @agents.each do |agent| %>
    <tr>
      <th scope="row"></th>
      <td><%= agent.first_name %></td>
      <td><%= agent.last_name %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/agents/new.html.erb
<h2><center>Create New Agent</center></h2>

<%= form_for @agent do |f| %>
  <div class="row">
      <div class="col-md-2">
        First name
      </div>
      <div class="col-md-10">
        <%= f.text_field :first_name, class: 'form-control agent_form_width' %>
      </div>
    </div>
    <div class="top20"></div>
    <div class="row">
      <div class="col-md-2">
        Last name
      </div>
      <div class="col-md-10">
        <%= f.text_field :last_name, class: 'form-control agent_form_width' %>
      </div>
    </div>
    <%= f.hidden_field :status, value: 'active' %>
    <div class="top20"></div>
    <%= f.submit 'Submit', class: 'btn btn-sm btn-primary' %>
<% end %>